plugin: gcp_compute
projects:
  - infra-253214
auth_kind: serviceaccount
service_account_file: ~/.gce/infra-253214-ansible.json
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
keyed_groups:
  # Create groups from GCE labels
  - prefix: ""
    separator: ""
    key: labels['group']
groups:
  env_stage: yes
