- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.0.3
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod
      tags:
        - db-tag

    - name: Fetch the latest version of application code
      git:
        repo: "https://github.com/express42/reddit.git"
        dest: /home/appuser/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma
      tags:
        - deploy-tag

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma
      tags:
        - app-tag

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
      tags:
        - app-tag

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags:
        - app-tag

  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted

    - name: reload puma
      become: true
      systemd: name=puma state=restarted
